/* 引擎的对外出口：theme/ 里的 React 薄包装只从这里 import。 */
export { loadRuntime, loadLibs, getRuntime, LibLoadError } from './runtime.ts';
export { STORE_KEY, PROGRESS_EVENT, emitProgress, progress, lp, drillRec, isDone } from './store.ts';
export { toast, loadingBox, errorBox, smooth } from './util.ts';
export { makePlayground, disposePlayground } from './playground.ts';
export { makeExercise } from './exercise.ts';
export { makeDrills, drillProgress } from './drills.ts';
export { makeTester, TestFail } from './tester.ts';
export { makeQuestion } from './question.ts';
export { makeQuiz } from './quiz.ts';
export { makeWarmup } from './warmup.ts';
export { makeSelfExplain } from './selfExplain.ts';
export { markTerms } from './terms.ts';
export { makeReview } from './review.ts';
export { makeCheck } from './stageCheck.ts';
export { attachStory } from './home.ts';
export { attachHeroTree, HERO_H, HERO_NODES, HERO_W, accName } from './home.ts';
export { offerResume, savePos } from './reading.ts';
export { doneCount, stageCount, dueCount, drillCount, lessonDrillCount } from './counts.ts';
export { drillRows, drillTotals } from './logic/drills.ts';
export { quizPassed, maybeComplete, paintFinish } from './completion.ts';
export { srsAll, srsRecord, cardRefOf, dueRefs, learnedRefs, resolveCards, srcLine } from './cards.ts';
export { loadLesson, loadLessons, loadedLesson, LessonLoadError } from './lessonData.ts';
export { DAY, SRS_DAYS } from './logic/srs.ts';
export { shuffled, seeded } from './logic/random.ts';
export { fmtOpt } from './logic/text.ts';
