// 由 scripts/convert.mjs 从旧版 src/*.js 生成。
// 术语表：课文里第一次出现的术语会自动加注（引擎 markTerms）。
export const GLOSSARY = [
  {
    term: '组件',
    en: 'component',
    def: '返回 JSX 的函数。名字以大写字母开头。',
    avoid: '模块；“控件”另指按钮、输入框这类元素（见“控件”）',
  },
  {
    term: 'JSX',
    en: 'JSX',
    def: '在 JavaScript 中描述界面的语法。编译后是创建元素的函数调用（新版是 jsx()，旧版是 createElement()）。',
    avoid: '',
  },
  {
    term: 'props',
    en: 'props',
    def: '父组件传给子组件的只读数据。描述传数据时写“通过 props 传入”。',
    avoid: '“属性”只用于 HTML 标签上的 attribute；不写“通过属性传入”',
  },
  {
    term: 'state',
    en: 'state',
    def: '组件自己保存、会变化的数据。用 set 函数传入新值，才会触发重新渲染。',
    avoid: '“状态”只用在固定词组中，例如“状态提升”“状态管理”',
  },
  {
    term: 'set 函数',
    en: 'set function',
    def: 'useState 返回的第二个值，例如 setCount。传入新值或更新函数，请求一次重新渲染。泛指时写“set 函数”，具体变量名照写。',
    avoid: 'setState（这是 class 组件的 API）、setter、修改函数',
  },
  {
    term: '唯一数据源',
    en: 'single source of truth',
    def: '同一份数据只在一处保存（通常是某个组件的 state）。其他组件通过 props 传入，或在渲染时由它算出。',
    avoid: '真相来源、唯一真相来源、单一数据源',
  },
  {
    term: '渲染',
    en: 'render',
    def: 'React 调用组件函数，计算出界面描述。渲染不修改 DOM。',
    avoid: '绘制',
  },
  {
    term: '重新渲染',
    en: 're-render',
    def: '组件自己或祖先组件的 state 变化后，或读取的 Context 变化后，React 再次调用组件函数。父组件重新渲染时，子组件默认也重新渲染。',
    avoid: '重渲染、重绘、刷新',
  },
  {
    term: '提交',
    en: 'commit',
    def: 'React 把渲染算出的差异应用到真实 DOM 的阶段。',
    avoid: '',
  },
  {
    term: '挂载',
    en: 'mount',
    def: '组件第一次出现在页面上。',
    avoid: '装载、加载',
  },
  {
    term: '卸载',
    en: 'unmount',
    def: '组件从页面上移除。',
    avoid: '销毁',
  },
  {
    term: '事件处理函数',
    en: 'event handler',
    def: '响应用户操作的函数，例如传给 onClick 的函数。',
    avoid: '处理器、监听器',
  },
  {
    term: 'Hook',
    en: 'Hook',
    def: '以 use 加大写字母开头的函数，例如 useState。只能在组件或自定义 Hook 的顶层调用。',
    avoid: '钩子',
  },
  {
    term: '自定义 Hook',
    en: 'custom Hook',
    def: '你自己写的、内部调用其他 Hook 的函数。用来复用逻辑。',
    avoid: '',
  },
  {
    term: 'effect',
    en: 'effect',
    def: '渲染提交后执行的代码。用来和外部系统同步。',
    avoid: '“副作用”只作为概念解释使用',
  },
  {
    term: '依赖数组',
    en: 'dependency array',
    def: 'useEffect、useMemo 等的第二个参数。React 用 Object.is 逐项比较。有一项变化，就重新执行 effect 或计算函数。',
    avoid: '依赖项列表',
  },
  {
    term: '清理函数',
    en: 'cleanup function',
    def: 'effect 返回的函数。在下次执行 effect 之前和卸载时运行。',
    avoid: '',
  },
  {
    term: '受控组件',
    en: 'controlled component',
    def: '值由 state 决定的表单元素。',
    avoid: '',
  },
  {
    term: 'key',
    en: 'key',
    def: '列表中每一项的稳定标识。React 用它匹配新旧元素。',
    avoid: '',
  },
  {
    term: 'ref',
    en: 'ref',
    def: '跨渲染保存的可变容器 { current }。修改它不触发重新渲染。',
    avoid: '引用（只在讲“引用相等”时使用）',
  },
  {
    term: 'Context',
    en: 'Context',
    def: '把数据传给整棵子树的机制。不需要逐层传 props。',
    avoid: '上下文',
  },
  {
    term: 'reducer',
    en: 'reducer',
    def: '纯函数 (state, action) => 新 state。集中描述 state 如何变化。',
    avoid: '',
  },
  {
    term: 'action',
    en: 'action',
    def: 'reducer 中描述“发生了什么”的对象，例如 { type: \'added\' }。路由和表单里处理提交的函数另称“路由 action”和“Server Function”。',
    avoid: '',
  },
  {
    term: 'dispatch',
    en: 'dispatch',
    def: '把 action 交给 reducer 的函数。',
    avoid: '',
  },
  {
    term: '纯函数',
    en: 'pure function',
    def: '同样的输入总是得到同样的输出，并且不修改外部数据的函数。',
    avoid: '',
  },
  {
    term: '闭包',
    en: 'closure',
    def: '函数记住它被创建时所在作用域的变量。',
    avoid: '',
  },
  {
    term: '记忆化',
    en: 'memoization',
    def: '依赖不变时，复用上一次的计算结果或引用。',
    avoid: '缓存（“缓存”只用于数据请求）',
  },
  {
    term: '协调',
    en: 'reconciliation',
    def: 'React 比较新旧元素树、找出差异的过程。',
    avoid: 'diff 过程',
  },
  {
    term: 'Fiber',
    en: 'Fiber',
    def: 'React 内部表示组件树的数据结构。它让渲染可以暂停和恢复。',
    avoid: '',
  },
  {
    term: '错误边界',
    en: 'error boundary',
    def: '捕获子树渲染错误并显示备用界面的组件。',
    avoid: '',
  },
  {
    term: '过渡更新',
    en: 'transition',
    def: '可以被打断的低优先级更新。',
    avoid: '非紧急更新',
  },
  {
    term: '服务端组件',
    en: 'Server Component',
    def: '在服务器上提前渲染的组件（构建时或每次请求时）。它的代码不发送到浏览器。',
    avoid: '服务器组件',
  },
  {
    term: '客户端组件',
    en: 'Client Component',
    def: '位于 \'use client\' 边界内的组件（在该文件定义或被它导入）。代码会发送到浏览器，首次加载时通常也在服务器预渲染成 HTML。',
    avoid: '',
  },
  {
    term: '水合',
    en: 'hydration',
    def: '浏览器为服务端生成的 HTML 绑定事件，使它可以交互。',
    avoid: '注水',
  },
  {
    term: 'Portal',
    en: 'portal',
    def: '把子节点的 DOM 放到另一个 DOM 节点中（常用 document.body）。在 React 树中位置不变，事件和 Context 照常传递。',
    avoid: '传送门',
  },
  {
    term: '浏览器绘制',
    en: 'paint',
    def: '浏览器把更新后的 DOM 画到屏幕上。发生在提交之后。useLayoutEffect 在它之前执行。',
    avoid: '“渲染”只指 React 调用组件函数',
  },
  {
    term: '无障碍',
    en: 'accessibility (a11y)',
    def: '让残障用户（看不见、不能用鼠标等）也能使用界面。',
    avoid: '可访问性、易用性',
  },
  {
    term: '控件',
    en: 'control',
    def: '用户可以操作的界面元素，例如按钮、输入框、复选框、下拉框。它不是 React 组件。',
    avoid: '“组件”只指 React 组件',
  },
  {
    term: '可访问名称',
    en: 'accessible name',
    def: '读屏软件读出的控件名字。来自 aria-labelledby、aria-label、label 或元素文字。',
    avoid: '无障碍名称、标签名',
  },
  {
    term: '焦点管理',
    en: 'focus management',
    def: '界面变化时，用代码把焦点移到合适的位置。例如弹窗关闭时把焦点还给触发按钮。',
    avoid: '',
  },
  {
    term: '实时区域',
    en: 'live region',
    def: '内容变化时读屏软件会自动读出的区域。用 role="status" 或 role="alert"。',
    avoid: '动态区域、播报区',
  },
  {
    term: 'Profiler',
    en: 'Profiler',
    def: 'React DevTools 中记录每次提交耗时的面板；也指 React 内置的 <Profiler> 组件。',
    avoid: '分析器',
  },
  {
    term: '虚拟列表',
    en: 'virtualization',
    def: '只渲染可见区域内的行，用占位高度保持滚动条长度。',
    avoid: '虚拟滚动、窗口化',
  },
  {
    term: '长任务',
    en: 'long task',
    def: '浏览器主线程上超过 50ms 的任务。期间页面不能响应操作。',
    avoid: '阻塞任务',
  },
  {
    term: '竞态',
    en: 'race condition',
    def: '结果取决于异步操作完成的先后顺序。常见情况：请求的返回顺序与发出顺序不同，导致显示旧数据。',
    avoid: '',
  },
  {
    term: '乐观更新',
    en: 'optimistic update',
    def: '请求完成前先显示预期结果；失败时回滚。',
    avoid: '',
  },
];
