// 由 scripts/gen-registry.mjs 生成，不要手改。运行 npm run gen 更新（dev、build 会自动运行；check:content 会检查它是否最新）。
// 课 id → 动态 import：每课一个异步 chunk（chunk 名 lesson-<id>）。
import type { Lesson } from './types.ts';

export const LESSON_LOADERS: Record<string, () => Promise<{ default: Lesson }>> = {
  'accessibility': () => import(/* webpackChunkName: "lesson-accessibility" */ './lessons/accessibility.ts'),
  'animation': () => import(/* webpackChunkName: "lesson-animation" */ './lessons/animation.ts'),
  'closures': () => import(/* webpackChunkName: "lesson-closures" */ './lessons/closures.ts'),
  'components-props': () => import(/* webpackChunkName: "lesson-components-props" */ './lessons/components-props.ts'),
  'concurrent': () => import(/* webpackChunkName: "lesson-concurrent" */ './lessons/concurrent.ts'),
  'conditional': () => import(/* webpackChunkName: "lesson-conditional" */ './lessons/conditional.ts'),
  'context': () => import(/* webpackChunkName: "lesson-context" */ './lessons/context.ts'),
  'custom-hooks': () => import(/* webpackChunkName: "lesson-custom-hooks" */ './lessons/custom-hooks.ts'),
  'delivery': () => import(/* webpackChunkName: "lesson-delivery" */ './lessons/delivery.ts'),
  'engineering': () => import(/* webpackChunkName: "lesson-engineering" */ './lessons/engineering.ts'),
  'error-handling': () => import(/* webpackChunkName: "lesson-error-handling" */ './lessons/error-handling.ts'),
  'escape-hatches': () => import(/* webpackChunkName: "lesson-escape-hatches" */ './lessons/escape-hatches.ts'),
  'events': () => import(/* webpackChunkName: "lesson-events" */ './lessons/events.ts'),
  'form-architecture': () => import(/* webpackChunkName: "lesson-form-architecture" */ './lessons/form-architecture.ts'),
  'forms': () => import(/* webpackChunkName: "lesson-forms" */ './lessons/forms.ts'),
  'headless-components': () => import(/* webpackChunkName: "lesson-headless-components" */ './lessons/headless-components.ts'),
  'jsx': () => import(/* webpackChunkName: "lesson-jsx" */ './lessons/jsx.ts'),
  'lifting-state': () => import(/* webpackChunkName: "lesson-lifting-state" */ './lessons/lifting-state.ts'),
  'lists-keys': () => import(/* webpackChunkName: "lesson-lists-keys" */ './lessons/lists-keys.ts'),
  'mini-react': () => import(/* webpackChunkName: "lesson-mini-react" */ './lessons/mini-react.ts'),
  'nextjs': () => import(/* webpackChunkName: "lesson-nextjs" */ './lessons/nextjs.ts'),
  'patterns': () => import(/* webpackChunkName: "lesson-patterns" */ './lessons/patterns.ts'),
  'perf-clinic': () => import(/* webpackChunkName: "lesson-perf-clinic" */ './lessons/perf-clinic.ts'),
  'performance': () => import(/* webpackChunkName: "lesson-performance" */ './lessons/performance.ts'),
  'portfolio': () => import(/* webpackChunkName: "lesson-portfolio" */ './lessons/portfolio.ts'),
  'profiling': () => import(/* webpackChunkName: "lesson-profiling" */ './lessons/profiling.ts'),
  'project-actions': () => import(/* webpackChunkName: "lesson-project-actions" */ './lessons/project-actions.ts'),
  'project-kanban': () => import(/* webpackChunkName: "lesson-project-kanban" */ './lessons/project-kanban.ts'),
  'project-search': () => import(/* webpackChunkName: "lesson-project-search" */ './lessons/project-search.ts'),
  'project-todo': () => import(/* webpackChunkName: "lesson-project-todo" */ './lessons/project-todo.ts'),
  'project-weather': () => import(/* webpackChunkName: "lesson-project-weather" */ './lessons/project-weather.ts'),
  'react-19': () => import(/* webpackChunkName: "lesson-react-19" */ './lessons/react-19.ts'),
  'rendering': () => import(/* webpackChunkName: "lesson-rendering" */ './lessons/rendering.ts'),
  'router': () => import(/* webpackChunkName: "lesson-router" */ './lessons/router.ts'),
  'scheduler': () => import(/* webpackChunkName: "lesson-scheduler" */ './lessons/scheduler.ts'),
  'server-components': () => import(/* webpackChunkName: "lesson-server-components" */ './lessons/server-components.ts'),
  'state-architecture': () => import(/* webpackChunkName: "lesson-state-architecture" */ './lessons/state-architecture.ts'),
  'state-at-scale': () => import(/* webpackChunkName: "lesson-state-at-scale" */ './lessons/state-at-scale.ts'),
  'state': () => import(/* webpackChunkName: "lesson-state" */ './lessons/state.ts'),
  'streaming-ssr': () => import(/* webpackChunkName: "lesson-streaming-ssr" */ './lessons/streaming-ssr.ts'),
  'styling': () => import(/* webpackChunkName: "lesson-styling" */ './lessons/styling.ts'),
  'suspense-data': () => import(/* webpackChunkName: "lesson-suspense-data" */ './lessons/suspense-data.ts'),
  'suspense': () => import(/* webpackChunkName: "lesson-suspense" */ './lessons/suspense.ts'),
  'tanstack-query': () => import(/* webpackChunkName: "lesson-tanstack-query" */ './lessons/tanstack-query.ts'),
  'testing': () => import(/* webpackChunkName: "lesson-testing" */ './lessons/testing.ts'),
  'typescript': () => import(/* webpackChunkName: "lesson-typescript" */ './lessons/typescript.ts'),
  'use-effect': () => import(/* webpackChunkName: "lesson-use-effect" */ './lessons/use-effect.ts'),
  'use-reducer': () => import(/* webpackChunkName: "lesson-use-reducer" */ './lessons/use-reducer.ts'),
  'use-ref': () => import(/* webpackChunkName: "lesson-use-ref" */ './lessons/use-ref.ts'),
  'what-is-react': () => import(/* webpackChunkName: "lesson-what-is-react" */ './lessons/what-is-react.ts'),
};
