// 课程顺序：全站唯一的课程顺序。课号 = 在这个数组里的位置（从 1 开始）。
// 侧栏、首页、翻页、热身、阶段测验都从这里（加上每课数据文件里的 stage）生成。
// 阶段归属写在每课数据文件的 stage 字段里（唯一的地方）；同一阶段的课必须连续排列（scripts/check-content.mjs 会检查）。
// 加一课：npm run new-lesson -- <课id> --stage <0-5> --after <已有课id> --title "标题"，会自动登记到这里。
export const LESSON_ORDER: string[] = [
  'what-is-react',
  'jsx',
  'components-props',
  'state',
  'events',
  'conditional',
  'lists-keys',
  'forms',
  'styling',
  'project-todo',
  'lifting-state',
  'use-reducer',
  'context',
  'use-ref',
  'use-effect',
  'custom-hooks',
  'project-search',
  'project-kanban',
  'rendering',
  'escape-hatches',
  'performance',
  'closures',
  'concurrent',
  'suspense',
  'profiling',
  'patterns',
  'accessibility',
  'animation',
  'state-architecture',
  'react-19',
  'server-components',
  'mini-react',
  'project-actions',
  'engineering',
  'delivery',
  'typescript',
  'router',
  'tanstack-query',
  'testing',
  'nextjs',
  'project-weather',
  'scheduler',
  'suspense-data',
  'streaming-ssr',
  'state-at-scale',
  'headless-components',
  'form-architecture',
  'error-handling',
  'perf-clinic',
  'portfolio',
];
