// 由 scripts/convert.mjs 从旧版 src/*.js 生成。
// 汇总全部已转换的课。引擎的热身、复习、阶段测验要跨课取题，都从这里拿。
import { LESSON_ORDER } from './order.js';
import l_what_is_react from './lessons/what-is-react.js';
import l_jsx from './lessons/jsx.js';
import l_components_props from './lessons/components-props.js';
import l_state from './lessons/state.js';
import l_events from './lessons/events.js';
import l_conditional from './lessons/conditional.js';
import l_lists_keys from './lessons/lists-keys.js';
import l_forms from './lessons/forms.js';
import l_project_todo from './lessons/project-todo.js';
import l_lifting_state from './lessons/lifting-state.js';
import l_use_reducer from './lessons/use-reducer.js';
import l_context from './lessons/context.js';
import l_use_ref from './lessons/use-ref.js';
import l_use_effect from './lessons/use-effect.js';
import l_custom_hooks from './lessons/custom-hooks.js';
import l_escape_hatches from './lessons/escape-hatches.js';
import l_project_search from './lessons/project-search.js';
import l_project_kanban from './lessons/project-kanban.js';
import l_rendering from './lessons/rendering.js';
import l_performance from './lessons/performance.js';
import l_closures from './lessons/closures.js';
import l_suspense from './lessons/suspense.js';
import l_concurrent from './lessons/concurrent.js';
import l_profiling from './lessons/profiling.js';
import l_patterns from './lessons/patterns.js';
import l_accessibility from './lessons/accessibility.js';
import l_state_architecture from './lessons/state-architecture.js';
import l_react_19 from './lessons/react-19.js';
import l_server_components from './lessons/server-components.js';
import l_mini_react from './lessons/mini-react.js';
import l_engineering from './lessons/engineering.js';
import l_typescript from './lessons/typescript.js';
import l_router from './lessons/router.js';
import l_tanstack_query from './lessons/tanstack-query.js';
import l_testing from './lessons/testing.js';
import l_nextjs from './lessons/nextjs.js';
import l_scheduler from './lessons/scheduler.js';
import l_suspense_data from './lessons/suspense-data.js';
import l_streaming_ssr from './lessons/streaming-ssr.js';
import l_state_at_scale from './lessons/state-at-scale.js';
import l_headless_components from './lessons/headless-components.js';
import l_form_architecture from './lessons/form-architecture.js';
import l_error_handling from './lessons/error-handling.js';
import l_perf_clinic from './lessons/perf-clinic.js';
import l_portfolio from './lessons/portfolio.js';

const ALL = [l_what_is_react, l_jsx, l_components_props, l_state, l_events, l_conditional, l_lists_keys, l_forms, l_project_todo, l_lifting_state, l_use_reducer, l_context, l_use_ref, l_use_effect, l_custom_hooks, l_escape_hatches, l_project_search, l_project_kanban, l_rendering, l_performance, l_closures, l_suspense, l_concurrent, l_profiling, l_patterns, l_accessibility, l_state_architecture, l_react_19, l_server_components, l_mini_react, l_engineering, l_typescript, l_router, l_tanstack_query, l_testing, l_nextjs, l_scheduler, l_suspense_data, l_streaming_ssr, l_state_at_scale, l_headless_components, l_form_architecture, l_error_handling, l_perf_clinic, l_portfolio];
// 按课程顺序排列。课号 = 在 LESSON_ORDER 里的位置（不是在 LESSONS 里的位置：未转换的课不在这里）
export const LESSONS = ALL.sort((a, b) => LESSON_ORDER.indexOf(a.id) - LESSON_ORDER.indexOf(b.id));
export const lessonNo = (id) => LESSON_ORDER.indexOf(id) + 1;
export const TOTAL_LESSONS = LESSON_ORDER.length;
export const lessonById = (id) => LESSONS.find((l) => l.id === id);
